### ISSUE TITLE
📺 /wizard/new

### ISSUE THREAD

**Issue by yeskunall** [talos-org/client#21]
# 📺 /wizard/new

## Requirements

- [x] Allow user to continue to next screen or exit on-boarding process
- _... more?_

## Screen 1 (Name of Blockchain and required details on-boarding screen)

- [x] Prompt user for new name of blockchain and ~other *required* fields (might only be name)~ to set up the blockchain (_only name is required_)

## Screen 2 (Blockchain configuration)

- [x] Allow user to configure advanced settings for blockchain (fields in MultiChain `conf` file)
~> @talos-org/back-end can one of you guys expand on this? What are the appropriate settings? I’m not sure and it’s not apparent from either of documents we’ve submitted so far.~
- [x] Allow user to accept defaults for advanced settings and skip the on-boarding process
> @talos-org/all what are the default settings?
- ~[ ] Validate that the settings configurations don't conflict with each other and min/max limits are not passed~
> We’re not doing this
- [x] Allow user to go back to first on-boarding screen, exit on-boarding, and continue

## Screen 3 (Review/Confirmation of New Blockchain)

- [x] Make user review name of blockchain, params/configuration
- [x] Allow user to go back to previous page, exit on-boarding, or continue/finish on-boarding
- [x] Create wrapper method that will call _Talos_ REST service endpoint for on-boarding and parse the response
- [x] Finish blockchain creation/configuration and redirect user to main Dashboard ~(tell user they need to add more nodes and where they can do so)~

**Comment by yeskunall** [comment]
> @talos-org/back-end can one of you guys expand on this? What are the appropriate settings? I’m not sure and it’s not apparent from either of documents we’ve submitted so far.
 

![image](https://user-images.githubusercontent.com/14703164/48680718-bece0180-eb6b-11e8-9043-70704a466b96.png)


Thank you @darshgrewal.

**Comment by darshgrewal** [comment]
The following parameters of a blockchain can be be configured after creating the chain but before starting the chain.The parameters are set in the params.dat file for each blockchain, and once the blockchain has been intialized these parameters can not be changed.
        :param blockchain_name: Blockchain to be changed
        :param description: Textual description of the blockchain for display to users.
        :param max_block_size: Maximum number of bytes in each block, to prevent network flooding by a rogue block creator.
        :param target_block_time: Target average number of seconds between blocks
        :param mining_turnover:A value of 0.0 prefers a pure round robin scheme between an automatically-discovered subset of the addresses with mine permissions,
        with others stepping in only if one fails. A value of 1.0 prefers pure random block creation between these addresses. Intermediate values set the balance
        between these two behaviors. Lower values reduce the number of forks, making the blockchain more efficient, but increase the level of validator concentration.
        :param mining_diversity:Minimum proportion of permitted “miners” required to participate in the round-robin scheme to render a valid blockchain, between 0.0 (no constraint) 
        and 1.0 (every address with mine permissions must participate).

**Comment by yeskunall** [comment]
![new-blockchain 2x](https://user-images.githubusercontent.com/14703164/53202725-40af4a00-35f5-11e9-86e0-b19fe996336a.png)

> What it is expected to look like

**Comment by yeskunall** [comment]
This is probably not gonna happen ^

> School is kicking our asses.
