### ISSUE TITLE
Data streams, data items, and data item editor pages

### ISSUE THREAD

**Issue by abungay** [talos-org/client#46]
Create pages for:
# Data streams:
- create, subscribe, unsubscribe, grant permissions
# Data items:
- list unique key names for a particular stream
- allow addition of a new key data item to stream
# Data item editor:
- show most recent version of a data item
- allowing editing/updating data of data item for a certain key
- show version history of item

**Comment by yeskunall** [comment]
Can you update this @abungay? It’s been in progress for over a month now.
