### ISSUE TITLE
Blockchain admin controls page

### ISSUE THREAD

**Issue by abungay** [talos-org/client#48]
Create the blockchain admin controls page

Support includes:
- allow incoming requests to connect to existing blockchain
- assign user permissions for entire blockchain
- etc

**Comment by yeskunall** [comment]
@DamanjitBhangoo can your provide some sort of update? Are you working on this ATM?

**Comment by DamanjitBhangoo** [comment]
@yeskunall still haven't had time to fix up the issues. I'll be working on it tomorrow and Saturday.
