### ISSUE TITLE
Talos logo cut off on welcome screen

### ISSUE THREAD

**Issue by abungay** [talos-org/client#60]
As seen below, we need to fix this styling bug for the logo on the welcome screen.
![Logo Bug](https://i.gyazo.com/f5c3d03563d83fb2b3b7afb3ca12573a.png)

**Comment by yeskunall** [comment]
![image](https://user-images.githubusercontent.com/14703164/54412940-acec0d80-46ca-11e9-99d2-c540613ff099.png)

Doesn’t seem cut off to me 🤔

Reopen if you still see this issue.
